"""add name and email fields to applications

Revision ID: a360a4b44062
Revises: 0d7ee8baa33c
Create Date: 2025-09-25 22:36:52.175012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a360a4b44062'
down_revision = '0d7ee8baa33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
